name: CI/CD Pipeline for Brainstorm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Display project structure
        run: |
          echo "Listing project structure:"
          ls -R